Repository Daniel-OC/whats-cookin, pull requests merged in 2022-01, with the labels that each got.

#60 Refactor/part1-css-feedback-AF
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#65 Feature/local-server-api-ect
  src/apiCalls.js
  src/classes/User.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: bug, enhancement, good first issue, question, Iteration 4!

#67 Feature/user-methods-ect
  src/apiCalls.js
  src/classes/User.js
  src/scripts.js
Labels: enhancement, refactor, Iteration 4!

#68 Refactor/event-delegation-ect
  src/apiCalls.js
  src/classes/User.js
  src/scripts.js
Labels: enhancement, refactor, Iteration 4!

#70 Feature/pantry-post-requests-AF
  src/index.html
  src/scripts.js
Labels: enhancement, Iteration 4!

#72 Feature/add specific ingredient doc
  src/index.html
  src/scripts.js
Labels: enhancement, refactor, Iteration 4!

#73 Feature/cook recipe remove ingredients doc
  src/classes/Pantry.js
  src/classes/User.js
  src/index.html
  src/scripts.js
Labels: enhancement, Iteration 4!

#75 Feature/sass-file-conversions-AF
  src/css/_keyframes.scss
  src/css/_mixins.scss
  src/css/_reset.scss
  src/css/_variables.scss
  src/css/index.scss
  src/index.html
  src/scripts.js
  webpack.config.js
Labels: documentation, enhancement

#77 Feature/dom update file ect
  src/domUpdates.js
  src/scripts.js
Labels: enhancement, refactor, Iteration 4!

#79 Refactor/ensure tests work doc
  src/classes/Pantry.js
  src/classes/Recipe.js
  src/data/testing-data/ingredients-test-data.js
  src/data/testing-data/recipe-test-data.js
  src/data/testing-data/user-test-data.js
  src/scripts.js
  test/Cookbook-test.js
  test/Pantry-test.js
  test/User-test.js
Labels: documentation, enhancement, iteration 3!, Iteration 4!

#81 Refactor/sass-button-hover-AF
  src/css/index.scss
  src/domUpdates.js
  src/index.html
Labels: enhancement, Iteration 4!

#84 Refactor/filter bug ect
  src/domUpdates.js
  src/index.html
  src/scripts.js
Labels: refactor, Iteration 4!

#86 Squash bug with filter between home and fav view
  src/domUpdates.js
  src/scripts.js
Labels: refactor, Iteration 4!
